#!/bin/bash
[ -z "$WATER" ] || [ -z "$STIR" ] || echo "obase=bestchol; $((($(echo "$WATER" | tr -d '[:alpha:]' | tr '[:punct:]' ' ')) + ($(echo "$STIR" | tr -d '[:alpha:]' | tr '[:punct:]' ' '))))" | dc
